### ISSUE TITLE
Create F-Droid build flavour

### ISSUE THREAD

**Issue by baldurmen** [michaelkourlas/voipms-sms-client#194]
The current release is 0.6.4 whereas the one on Fdroid is stuck on 0.6.1 :)

Since you still publish new -fdroid releases, I guess something in their build process broke...

**Comment by michaelkourlas** [comment]
Unfortunately I have no control over their build process -- you'll have to contact them.

**Comment by baldurmen** [comment]
I read FDroid's doc on how they manage builds and made Merge Request to fix this issue. I'll close this once it's been merged.

https://gitlab.com/fdroid/fdroiddata/merge_requests/5628/

**Comment by licaon-kter** [comment]
@michaelkourlas You've published 0.6.4-fdroid as APK, ok... but where's the source code for that? I only see 0.6.3 in the fdroid branch.

**Comment by michaelkourlas** [comment]
Sorry, I forgot to push those changes. They should be up now.

**Comment by baldurmen** [comment]
Hmm, that took some work and I'm not sure I understand if autoupdates can be enabled, but for now I'll subscribe to releases here and push them to Fdroid in the future.

If someone wants to have a look at enabling autoupdates, that'd be nice though :)

**Comment by licaon-kter** [comment]
@baldurmen Autoupdates work best with Tags, now we need to follow commits in a manual way, because main Tags are not for F-Droid.

So having a fdroid gradle flavour is recommended, instead of this branch thing.

**Comment by michaelkourlas** [comment]
I agree the branch is a bit of hack. I'll look into making a dedicated flavour.

**Comment by michaelkourlas** [comment]
@baldurmen @licaon-kter I've added an F-Droid build flavour and removed the branch.

**Comment by licaon-kter** [comment]
@michaelkourlas Ok, it builds fine

```
  - versionName: 0.6.5-fdroid
    versionCode: 123
    commit: 954be016e49932b6e9beed0a72c4518c41f2f066
    subdir: voipms-sms
    gradle:
      - fdroid
    prebuild:
      - sed -i -e '/google-services/d' -e '/fabric/d' -e '/whenTaskAdded/,+6d' build.gradle ../build.gradle
```
